### ISSUE TITLE
官方什么时候才支持flutter3版本啊？

### ISSUE THREAD

**Issue by xiaodeji** [LianjiaTech/bruno#245]
希望能给个时间

**Comment by overMiracle** [comment]
很多插件都升级到3.0了，官网能不能先处理下这个问题？

**Comment by wxuonline** [comment]
这个组件库有问题得自己想办法解决，
目前官方的2.10.x分支是有支持兼容flutter3.0
```
bruno:
        git:
            url: https://github.com/LianjiaTech/bruno.git
            branch: 2.10.x
```
如果一定要用master分子的代码的话，也可以自己fork一下代码，然后在master分支上手动把3.0报错的地方改掉
再或者用我这边的代码也行
```
bruno:
        git:
            url: https://github.com/wxuonline/bruno.git
            branch: master
```
