### ISSUE TITLE
No named parameter with the name 'brightness'.       brightness: brightness ?? Brightness.light,

### ISSUE THREAD

**Issue by lxhyz** [LianjiaTech/bruno#462]
## 问题提交
bruno3.3.0，本地flutter sdk version 3.0.2
标题格式：[BUG]: 问题简介

内容需包含：

**1、BUG 描述**

问题的描述，请尽量使用简短、准确的语言

**2、复现步骤**

**3、期望行为**

**4、运行环境**

* 运行设备 andriod
* 系统 window
* Bruno 版本 3.3.2
* Flutter Doctor 信息

**5、附加信息**

包括视频、图片等补充信息

**Comment by BingKui** [comment]
这个bug是因为 Flutter 2.0 移除了这个属性，改用 Theme 了，所以可以把这个删了就行了。
可以用我修改后的库：https://github.com/BingKui/bruno.git
修改`pubspec.yaml` 文件:
```yaml
bruno:
    git:
      url: https://github.com/BingKui/bruno.git
```

即可解决报错问题。
